import java.util.ArrayList;
import java.util.Random;
//Write a Java application with a thread that generates 30 random numbers
// between 0 and 30. Another thread displays the area of the circles having as radiuses
// the values divisible by 3 generated by the first thread.
class Thread1 extends Thread{
    public ArrayList<Integer> nr;

    public Thread1() {
        nr = new ArrayList<Integer>();
        System.out.println("Thread 1 created!");
    }

    public void run() {
        Random random=new Random();
        for (int i = 0; i < 30; i++) {

            nr.add(i, random.nextInt(0,30));
            System.out.println("The generated number is: "+ nr.get(i));
        }
    }
    public ArrayList<Integer> getNr(){
        return nr;
    }

}

class Thread2 extends Thread {
    ArrayList<Integer> nrs;

    Thread2 (ArrayList<Integer> nr)
    {
        this.nrs=nr;
        System.out.println("Thread 2 created!");
    }

    public void run()
    {
        for (Integer nr : nrs)
        {
            if (nr % 3 == 0)
            {
                System.out.println("The area of the circle is: "+ (nr * nr *3.14));
            }
        }
    }


}
public class HorvathDaiana_lab9pb2 {
    public static void main(String[] args) {
        Thread1 thread1=new Thread1();

        thread1.start();


        try {
            thread1.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("Thread 1 finished the task!");
        ArrayList<Integer> nrs = thread1.getNr();


        Thread2 thread2 = new Thread2(nrs);
        thread2.start();
        try {
            thread2.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("All threads finished their tasks!");
    }
}